### ISSUE TITLE
Getting wrong byte value

### ISSUE THREAD

**Issue by thbl** [noopkat/png-to-lcd#16]
Hi
Nice project just what i was looking for, trying to use it for a eink display.
Could you explain how you calculate the byte / "pageShift" ? or where i can read more about it.

For my display i get the wrong byte value.
example
i get 127 (7F) but i want to get 254 (FE)
Thanks

**Comment by noopkat** [comment]
Hi @thbl thanks for opening this issue.

This library is designed to be compatible with the [SSD1306 OLED](https://cdn-shop.adafruit.com/datasheets/SSD1306.pdf) display driver interface only, sorry for the confusion! I will go ahead and update the documentation in the README to clarify this as the wording was not 100% clear.

Sorry that I can't help you with this library for your eink display - you'll need to hunt for one that's compatible.

**Comment by thbl** [comment]
Hi @noopkat 

I found the issue to be that my eink display uses a different scan mode. (bottom to top instead of top to bottom)
I solved this by reversing bits for each byte (pageShift) in the buffer.

Thanks for your reply any ways, and your library which have helped me out on my project.
